# Generated by Django 5.0.6 on 2024-05-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseName', models.CharField(max_length=100)),
                ('CourseDuration', models.CharField(max_length=100)),
                ('WeeklyClass', models.CharField(max_length=100)),
                ('ClassDurationHour', models.CharField(max_length=100)),
                ('ClassDurationMinute', models.CharField(max_length=100)),
                ('CourseFee', models.CharField(max_length=100)),
                ('AboutCourse', models.CharField(max_length=100)),
                ('CourseTopics', models.CharField(max_length=100)),
                ('CourseImage', models.ImageField(upload_to='static/courseImg/')),
            ],
        ),
    ]
