# Generated by Django 5.0.6 on 2024-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionformmodel',
            name='StudentPhoto',
            field=models.ImageField(upload_to='pendingstudent'),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseImage',
            field=models.ImageField(upload_to='courseImg'),
        ),
        migrations.AlterField(
            model_name='galleryimagemodel',
            name='GalleryImage',
            field=models.ImageField(upload_to='galleryImage'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='StudentPhoto',
            field=models.ImageField(upload_to='pendingstudent'),
        ),
        migrations.AlterField(
            model_name='successfulstudentinfomodel',
            name='StudentImage',
            field=models.ImageField(upload_to='successStudent'),
        ),
    ]
