# Generated by Django 5.0.6 on 2024-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0002_courseinfomodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfomodel',
            name='AboutCourse',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseTopics',
            field=models.TextField(),
        ),
    ]
