# Generated by Django 5.0.6 on 2024-05-31 19:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0002_batchinfomodel_batchstart'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchinfomodel',
            name='Status',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
