# Generated by Django 5.0.6 on 2024-05-30 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0002_alter_admissionformmodel_studentphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseinfomodel',
            name='NoOfStudents',
        ),
    ]
