# Generated by Django 5.0.6 on 2024-06-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0002_admissionformmodel_emergencymobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionformmodel',
            name='PermanentAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='admissionformmodel',
            name='Qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
