# Generated by Django 5.0.6 on 2024-09-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0002_admissionformmodel_emergencymobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File_Title', models.CharField(max_length=100, null=True)),
                ('File', models.FileField(null=True, upload_to='BlogFile')),
            ],
        ),
    ]
