# Generated by Django 5.0.6 on 2024-05-30 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0003_remove_courseinfomodel_noofstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionformmodel',
            name='CourseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RainbowApp.courseinfomodel'),
        ),
    ]
