# Generated by Django 5.0.6 on 2024-09-07 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0003_blogfilemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Title', models.CharField(max_length=100, null=True)),
                ('Video_Description', models.TextField(null=True)),
                ('Video_Url', models.CharField(max_length=200, null=True)),
                ('Posted_Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
