# Generated by Django 5.0.6 on 2024-05-31 19:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0003_batchinfomodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfomodel',
            name='Batchschedule',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='Section',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
