# Generated by Django 5.0.6 on 2024-05-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0004_alter_admissionformmodel_coursename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='StudentPhoto',
            field=models.ImageField(upload_to='studentphoto'),
        ),
    ]
