# Generated by Django 5.0.6 on 2024-09-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0004_blogvideomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideomodel',
            name='Video_Thumbnail',
            field=models.ImageField(null=True, upload_to='VideoThumbnail/'),
        ),
    ]
