# Generated by Django 5.0.6 on 2024-09-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0004_studentinfomodel_qualification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicsName', models.CharField(max_length=150, null=True)),
                ('Files', models.FileField(null=True, upload_to='blogfiles')),
            ],
        ),
    ]
