# Generated by Django 5.0.6 on 2024-06-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0004_studentinfomodel_batchschedule_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('Facebook', models.CharField(max_length=100)),
                ('MapLink', models.TextField()),
            ],
        ),
    ]
