# Generated by Django 5.0.6 on 2024-05-28 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0005_successfulstudentinfomodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='successfulstudentinfomodel',
            old_name='CourseImage',
            new_name='StudentImage',
        ),
    ]
