# Generated by Django 5.0.6 on 2024-09-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0005_blogvideomodel_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideomodel',
            name='Video_Category',
            field=models.CharField(choices=[('Ms Word', 'Ms Word'), ('Ms Excel', 'Ms Powerpoint'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
