# Generated by Django 5.0.6 on 2024-06-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0005_contactusmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfomodel',
            name='BatchNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='batchinfomodel', to='RainbowApp.batchinfomodel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='CourseName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='courseinfomodel', to='RainbowApp.courseinfomodel'),
        ),
    ]
