# Generated by Django 5.0.6 on 2024-06-04 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0006_alter_studentinfomodel_batchno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionformmodel',
            name='Address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RainbowApp.courseinfomodel'),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='FatherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='Mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='MotherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='StudentName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='StudentPhoto',
            field=models.ImageField(null=True, upload_to='pendingstudent'),
        ),
        migrations.AlterField(
            model_name='admissionformmodel',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchinfomodel',
            name='BatchNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchinfomodel',
            name='Batchschedule',
            field=models.CharField(choices=[('09:00 AM - 10:00 AM', '09:00 AM - 10:00 AM'), ('10:00 AM - 11:30 AM', '10:00 AM - 11:30 AM'), ('11:30 AM - 01:00 PM', '11:30 AM - 01:00 PM'), ('01:00 PM - 02:30 PM', '01:00 PM - 02:30 PM'), ('03:00 PM - 04:30 PM', '03:00 PM - 04:30 PM'), ('04:30 PM - 06:00 PM', '04:30 PM - 06:00 PM'), ('06:00 PM - 07:30 PM', '06:00 PM - 07:30 PM'), ('08:00 PM - 09:30 PM', '08:00 PM - 09:30 PM')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchinfomodel',
            name='Section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='batchinfomodel',
            name='Status',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='Email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='Facebook',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='MapLink',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='contactusmodel',
            name='Mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='AboutCourse',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='ClassDurationHour',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='ClassDurationMinute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseDuration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseFee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseImage',
            field=models.ImageField(null=True, upload_to='courseImg'),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='CourseTopics',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courseinfomodel',
            name='WeeklyClass',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='UserType',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Student', 'Student')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='galleryimagemodel',
            name='GalleryImage',
            field=models.ImageField(null=True, upload_to='galleryImage'),
        ),
        migrations.AlterField(
            model_name='galleryimagemodel',
            name='ImageTitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serviceinfomodel',
            name='AboutService',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='serviceinfomodel',
            name='ServiceName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='BatchNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchinfomodel', to='RainbowApp.batchinfomodel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Batchschedule',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='CourseFee',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseinfomodel', to='RainbowApp.courseinfomodel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Due',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='EmergencyMobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='FatherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='MotherName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Payment',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='PermanentAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='PresentAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Religion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='RollNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='Section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='StudentName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='StudentPhoto',
            field=models.ImageField(null=True, upload_to='studentphoto'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentuser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='successfulstudentinfomodel',
            name='StudentDesignation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='successfulstudentinfomodel',
            name='StudentImage',
            field=models.ImageField(null=True, upload_to='successStudent'),
        ),
        migrations.AlterField(
            model_name='successfulstudentinfomodel',
            name='StudentInstitute',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='successfulstudentinfomodel',
            name='StudentName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
