# Generated by Django 5.0.6 on 2024-05-28 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0006_rename_courseimage_successfulstudentinfomodel_studentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageTitle', models.CharField(max_length=100)),
                ('GalleryImage', models.ImageField(upload_to='static/galleryImage/')),
            ],
        ),
    ]
