# Generated by Django 5.0.6 on 2024-06-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0007_alter_admissionformmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionformmodel',
            name='StudentPhoto',
            field=models.ImageField(null=True, upload_to='studentphoto'),
        ),
    ]
