# Generated by Django 5.0.6 on 2024-06-02 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0007_alter_admissionformmodel_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionformmodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RainbowApp.courseinfomodel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='BatchNo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batchinfomodel', to='RainbowApp.batchinfomodel'),
        ),
        migrations.AlterField(
            model_name='studentinfomodel',
            name='CourseName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseinfomodel', to='RainbowApp.courseinfomodel'),
        ),
    ]
