# Generated by Django 5.0.6 on 2024-06-05 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0009_alter_studentinfomodel_studentphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResultModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamTitle', models.CharField(max_length=100, null=True)),
                ('MCQ', models.CharField(max_length=100, null=True)),
                ('Written', models.CharField(max_length=100, null=True)),
                ('Practicle', models.CharField(max_length=100, null=True)),
                ('TotalMark', models.CharField(max_length=100, null=True)),
                ('ExamDate', models.DateField(null=True)),
                ('Candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examinfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
