# Generated by Django 5.0.6 on 2024-05-28 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0011_alter_admissionformmodel_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StudentName', models.CharField(max_length=100)),
                ('FatherName', models.CharField(max_length=100)),
                ('MotherName', models.CharField(max_length=100)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100)),
                ('DOB', models.DateField()),
                ('Religion', models.CharField(max_length=100)),
                ('Mobile', models.CharField(max_length=100)),
                ('EmergencyMobile', models.CharField(max_length=100)),
                ('StudentPhoto', models.ImageField(upload_to='static/pendingstudent/')),
                ('PresentAddress', models.CharField(max_length=100)),
                ('PermanentAddress', models.CharField(max_length=100)),
                ('RollNo', models.CharField(max_length=100)),
                ('CourseName', models.CharField(max_length=100)),
                ('Batch', models.CharField(max_length=100)),
                ('Section', models.CharField(max_length=100)),
                ('CourseFee', models.CharField(max_length=100)),
                ('Payment', models.CharField(max_length=100)),
                ('Due', models.CharField(max_length=100)),
                ('AdmissionDate', models.DateField(auto_now_add=True)),
                ('LastModified', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='studentuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
