# Generated by Django 5.0.6 on 2024-05-29 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0012_studentinfomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfomodel',
            name='NoOfStudents',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
