# Generated by Django 5.0.6 on 2024-05-29 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RainbowApp', '0013_courseinfomodel_noofstudents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfomodel',
            old_name='Batch',
            new_name='BatchNo',
        ),
        migrations.AddField(
            model_name='studentinfomodel',
            name='Batchschedule',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
